name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - name: Build Project
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: '${{ secrets.VITE_FIREBASE_API_KEY }}'
          VITE_FIREBASE_AUTH_DOMAIN: '${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}'
          VITE_FIREBASE_PROJECT_ID: '${{ secrets.VITE_FIREBASE_PROJECT_ID }}'
          VITE_FIREBASE_STORAGE_BUCKET: '${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}'
          VITE_FIREBASE_MESSAGING_SENDER_ID: '${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}'
          VITE_FIREBASE_APP_ID: '${{ secrets.VITE_FIREBASE_APP_ID }}'
          VITE_FIREBASE_MEASUREMENT_ID: '${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}'
          VITE_GOOGLE_GEN_AI_KEY: '${{ secrets.VITE_GOOGLE_GEN_AI_KEY }}'
      - name: Verify Build Output
        run: ls -R dist
      - name: Deploy to Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HEALTH_TRACKER }}' > service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/service-account.json
          npx firebase-tools deploy --only hosting --project health-tracker-app-1cc9d --json
        env:
          VITE_FIREBASE_API_KEY: '${{ secrets.VITE_FIREBASE_API_KEY }}'
